/**
 * Supabase Database Types
 *
 * This file contains TypeScript types for the Supabase database schema.
 * These types should be regenerated when the database schema changes using:
 *
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts
 *
 * For now, this is a placeholder with the expected schema structure.
 * The actual types will be generated once the Supabase project is set up.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

/**
 * Clothing categories enum
 */
export type ClothingCategory =
  | 'top' // Hauts (t-shirts, chemises, pulls)
  | 'bottom' // Bas (pantalons, jupes, shorts)
  | 'dress' // Robes
  | 'outerwear' // Vestes, manteaux
  | 'shoes' // Chaussures
  | 'accessory'; // Accessoires

/**
 * Primary colors for clothing
 */
export type ClothingColor =
  | 'black'
  | 'white'
  | 'gray'
  | 'navy'
  | 'blue'
  | 'red'
  | 'pink'
  | 'green'
  | 'yellow'
  | 'orange'
  | 'purple'
  | 'brown'
  | 'beige'
  | 'multicolor';

/**
 * Subscription status
 */
export type SubscriptionStatus =
  | 'trial' // 7-day free trial
  | 'active' // Paying subscriber
  | 'cancelled' // Cancelled but active until period end
  | 'expired'; // No longer active

export interface Database {
  public: {
    Tables: {
      /**
       * User profiles (multi-profile support, max 3 for MVP)
       * Each user can have multiple profiles (e.g., parent + children)
       */
      profiles: {
        Row: {
          id: string;
          user_id: string;
          display_name: string;
          avatar_url: string | null;
          birth_date: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          display_name: string;
          avatar_url?: string | null;
          birth_date?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          display_name?: string;
          avatar_url?: string | null;
          birth_date?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      /**
       * Clothing items in the wardrobe
       * Each item belongs to a specific profile
       */
      clothes: {
        Row: {
          id: string;
          profile_id: string;
          category: ClothingCategory;
          color: ClothingColor;
          original_image_url: string;
          processed_image_url: string | null;
          notes: string | null;
          last_worn_at: string | null;
          wear_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          category: ClothingCategory;
          color: ClothingColor;
          original_image_url: string;
          processed_image_url?: string | null;
          notes?: string | null;
          last_worn_at?: string | null;
          wear_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          category?: ClothingCategory;
          color?: ClothingColor;
          original_image_url?: string;
          processed_image_url?: string | null;
          notes?: string | null;
          last_worn_at?: string | null;
          wear_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'clothes_profile_id_fkey';
            columns: ['profile_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };

      /**
       * Daily outfit recommendations
       * Generated by the algorithm based on weather, rotation, and discovery
       */
      outfit_recommendations: {
        Row: {
          id: string;
          profile_id: string;
          date: string;
          weather_temp: number | null;
          weather_condition: string | null;
          outfit_items: Json; // Array of clothing IDs
          is_selected: boolean;
          feedback: 'positive' | 'negative' | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          date: string;
          weather_temp?: number | null;
          weather_condition?: string | null;
          outfit_items: Json;
          is_selected?: boolean;
          feedback?: 'positive' | 'negative' | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          date?: string;
          weather_temp?: number | null;
          weather_condition?: string | null;
          outfit_items?: Json;
          is_selected?: boolean;
          feedback?: 'positive' | 'negative' | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'outfit_recommendations_profile_id_fkey';
            columns: ['profile_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };

      /**
       * User settings and preferences
       */
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          notification_enabled: boolean;
          notification_time: string; // HH:MM format
          city: string | null;
          use_geolocation: boolean;
          subscription_status: SubscriptionStatus;
          trial_start_date: string | null;
          subscription_start_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          notification_enabled?: boolean;
          notification_time?: string;
          city?: string | null;
          use_geolocation?: boolean;
          subscription_status?: SubscriptionStatus;
          trial_start_date?: string | null;
          subscription_start_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          notification_enabled?: boolean;
          notification_time?: string;
          city?: string | null;
          use_geolocation?: boolean;
          subscription_status?: SubscriptionStatus;
          trial_start_date?: string | null;
          subscription_start_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_settings_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      /**
       * RGPD consent tracking
       */
      user_consents: {
        Row: {
          id: string;
          user_id: string;
          consent_type: string;
          consented: boolean;
          consented_at: string;
          ip_address: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          consent_type: string;
          consented: boolean;
          consented_at?: string;
          ip_address?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          consent_type?: string;
          consented?: boolean;
          consented_at?: string;
          ip_address?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'user_consents_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
    };

    Views: {
      [_ in never]: never;
    };

    Functions: {
      [_ in never]: never;
    };

    Enums: {
      clothing_category: ClothingCategory;
      clothing_color: ClothingColor;
      subscription_status: SubscriptionStatus;
    };

    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Helper types for easier usage
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert'];
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update'];

export type Clothing = Database['public']['Tables']['clothes']['Row'];
export type ClothingInsert = Database['public']['Tables']['clothes']['Insert'];
export type ClothingUpdate = Database['public']['Tables']['clothes']['Update'];

export type OutfitRecommendation = Database['public']['Tables']['outfit_recommendations']['Row'];
export type OutfitRecommendationInsert =
  Database['public']['Tables']['outfit_recommendations']['Insert'];

export type UserSettings = Database['public']['Tables']['user_settings']['Row'];
export type UserSettingsInsert = Database['public']['Tables']['user_settings']['Insert'];
export type UserSettingsUpdate = Database['public']['Tables']['user_settings']['Update'];
