#!/bin/bash
# Burn-In Loop Script
# Runs tests multiple times to detect flaky tests
# Generated by BMad TestArch CI workflow

set -e

# Default iterations
ITERATIONS=${1:-10}

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔥 Burn-In Loop: $ITERATIONS iterations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Purpose: Detect non-deterministic (flaky) tests"
echo "Usage: ./scripts/burn-in.sh [iterations]"
echo ""

START_TIME=$(date +%s)
PASSED=0
FAILED=0

for i in $(seq 1 $ITERATIONS); do
    echo "────────────────────────────────────────────────────"
    echo "🔥 Iteration $i/$ITERATIONS"
    echo "────────────────────────────────────────────────────"

    if pnpm test -- --silent; then
        PASSED=$((PASSED + 1))
        echo "✓ Passed"
    else
        FAILED=$((FAILED + 1))
        echo ""
        echo "❌ FAILED at iteration $i"
        echo ""
        echo "This indicates a flaky test. Investigation required:"
        echo "  1. Run: pnpm test -- --verbose"
        echo "  2. Check for race conditions"
        echo "  3. Check for shared state between tests"
        echo "  4. Check for time-dependent assertions"
        echo ""

        # Continue running to see failure rate
        if [ $i -lt $ITERATIONS ]; then
            echo "Continuing to measure flakiness rate..."
        fi
    fi
    echo ""
done

END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))
RATE=$((PASSED * 100 / ITERATIONS))

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Burn-In Results"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Iterations: $ITERATIONS"
echo "   Passed:     $PASSED"
echo "   Failed:     $FAILED"
echo "   Success:    $RATE%"
echo "   Duration:   ${DURATION}s"
echo ""

if [ $FAILED -eq 0 ]; then
    echo "✅ All iterations passed! Tests are stable."
    exit 0
else
    echo "❌ $FAILED flaky test(s) detected! Fix before merging."
    exit 1
fi
