#!/bin/bash
# CI Local Mirror Script
# Mirrors the CI pipeline locally for debugging before pushing
# Generated by BMad TestArch CI workflow

set -e

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Running CI Pipeline Locally"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Track timing
START_TIME=$(date +%s)

# Stage 1: Lint
echo "📋 Stage 1/4: Lint & TypeCheck"
echo "────────────────────────────────────────────────────"
pnpm lint || { echo "❌ Lint failed"; exit 1; }
pnpm typecheck || { echo "❌ TypeCheck failed"; exit 1; }
echo "✓ Lint & TypeCheck passed"
echo ""

# Stage 2: Tests
echo "🧪 Stage 2/4: Unit Tests"
echo "────────────────────────────────────────────────────"
pnpm test -- --coverage || { echo "❌ Tests failed"; exit 1; }
echo "✓ Tests passed"
echo ""

# Stage 3: Expo Doctor
echo "🩺 Stage 3/4: Expo Doctor"
echo "────────────────────────────────────────────────────"
pnpm expo:doctor || echo "⚠️ Expo doctor completed with warnings"
echo ""

# Stage 4: Mini burn-in (3 iterations instead of 10)
echo "🔥 Stage 4/4: Mini Burn-In (3 iterations)"
echo "────────────────────────────────────────────────────"
for i in {1..3}; do
    echo "  Iteration $i/3..."
    pnpm test -- --silent || {
        echo "❌ Flaky test detected at iteration $i"
        exit 1
    }
done
echo "✓ Burn-in passed (no flaky tests detected)"
echo ""

# Summary
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Local CI Pipeline Passed!"
echo "   Duration: ${DURATION}s"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
