#!/bin/bash
# Selective Testing Script
# Runs only tests for changed files (faster feedback)
# Generated by BMad TestArch CI workflow

set -e

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 Running Tests for Changed Files"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get changed files (staged + unstaged)
CHANGED_FILES=$(git diff --name-only HEAD 2>/dev/null || git diff --name-only)

if [ -z "$CHANGED_FILES" ]; then
    echo "No changed files detected."
    echo "Running all tests instead..."
    pnpm test
    exit 0
fi

echo "Changed files:"
echo "$CHANGED_FILES" | sed 's/^/  /'
echo ""

# Check if any source files changed
if echo "$CHANGED_FILES" | grep -qE '\.(ts|tsx|js|jsx)$'; then
    echo "Source files changed - running related tests..."

    # Extract test patterns from changed files
    PATTERNS=""
    for file in $CHANGED_FILES; do
        # Convert source path to test pattern
        if [[ $file =~ \.(ts|tsx|js|jsx)$ ]]; then
            basename=$(basename "$file" | sed 's/\.[^.]*$//')
            PATTERNS="$PATTERNS $basename"
        fi
    done

    if [ -n "$PATTERNS" ]; then
        echo "Test patterns:$PATTERNS"
        echo ""
        pnpm test -- --testPathPattern="$(echo $PATTERNS | tr ' ' '|')" || {
            echo ""
            echo "⚠️ Selective tests failed. Running full suite for verification..."
            pnpm test
        }
    else
        pnpm test
    fi
else
    echo "No source files changed - skipping tests."
    echo "Changed files were: config, assets, docs, etc."
fi

echo ""
echo "✅ Selective testing complete"
