-- ============================================
-- Dressing Intelligent - Initial Database Schema
-- ============================================
-- Date: 2026-02-01
-- Description: Creates the initial database schema for the Dressing Intelligent app
-- Includes: profiles, clothes, outfit_recommendations, user_settings, user_consents
-- Security: Row Level Security (RLS) enabled on all tables

-- ============================================
-- EXTENSIONS
-- ============================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- ENUMS
-- ============================================

-- Clothing categories
CREATE TYPE clothing_category AS ENUM (
  'top',        -- Hauts (t-shirts, chemises, pulls)
  'bottom',     -- Bas (pantalons, jupes, shorts)
  'dress',      -- Robes
  'outerwear',  -- Vestes, manteaux
  'shoes',      -- Chaussures
  'accessory'   -- Accessoires
);

-- Primary colors for clothing
CREATE TYPE clothing_color AS ENUM (
  'black',
  'white',
  'gray',
  'navy',
  'blue',
  'red',
  'pink',
  'green',
  'yellow',
  'orange',
  'purple',
  'brown',
  'beige',
  'multicolor'
);

-- Subscription status
CREATE TYPE subscription_status AS ENUM (
  'trial',      -- 7-day free trial
  'active',     -- Paying subscriber
  'cancelled',  -- Cancelled but active until period end
  'expired'     -- No longer active
);

-- Feedback type
CREATE TYPE feedback_type AS ENUM (
  'positive',
  'negative'
);

-- ============================================
-- TABLES
-- ============================================

-- --------------------------------------------
-- PROFILES TABLE
-- User profiles (multi-profile support, max 3 for MVP)
-- Each user can have multiple profiles (e.g., parent + children)
-- --------------------------------------------
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name VARCHAR(100) NOT NULL,
  avatar_url TEXT,
  birth_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Constraint: Max 3 profiles per user (MVP)
  CONSTRAINT unique_profile_per_user UNIQUE (user_id, display_name)
);

-- Index for fast profile lookups by user
CREATE INDEX idx_profiles_user_id ON profiles(user_id);

-- --------------------------------------------
-- CLOTHES TABLE
-- Clothing items in the wardrobe
-- Each item belongs to a specific profile
-- --------------------------------------------
CREATE TABLE clothes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  category clothing_category NOT NULL,
  color clothing_color NOT NULL,
  original_image_url TEXT NOT NULL,
  processed_image_url TEXT, -- After background removal
  notes TEXT,
  last_worn_at TIMESTAMPTZ,
  wear_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for wardrobe queries
CREATE INDEX idx_clothes_profile_id ON clothes(profile_id);
CREATE INDEX idx_clothes_category ON clothes(profile_id, category);
CREATE INDEX idx_clothes_last_worn ON clothes(profile_id, last_worn_at);

-- --------------------------------------------
-- OUTFIT RECOMMENDATIONS TABLE
-- Daily outfit recommendations generated by the algorithm
-- Based on weather, rotation, and discovery
-- --------------------------------------------
CREATE TABLE outfit_recommendations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  weather_temp NUMERIC(4,1), -- Temperature in Celsius
  weather_condition VARCHAR(50),
  outfit_items JSONB NOT NULL, -- Array of clothing IDs
  is_selected BOOLEAN NOT NULL DEFAULT FALSE,
  feedback feedback_type,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- One recommendation set per profile per day
  CONSTRAINT unique_recommendation_per_day UNIQUE (profile_id, date)
);

-- Indexes for recommendation queries
CREATE INDEX idx_outfit_recommendations_profile_date ON outfit_recommendations(profile_id, date DESC);

-- --------------------------------------------
-- USER SETTINGS TABLE
-- User settings and preferences
-- --------------------------------------------
CREATE TABLE user_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  notification_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  notification_time TIME NOT NULL DEFAULT '07:00:00', -- Default 7 AM
  city VARCHAR(100),
  use_geolocation BOOLEAN NOT NULL DEFAULT FALSE,
  subscription_status subscription_status NOT NULL DEFAULT 'trial',
  trial_start_date TIMESTAMPTZ,
  subscription_start_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for user settings lookup
CREATE INDEX idx_user_settings_user_id ON user_settings(user_id);

-- --------------------------------------------
-- USER CONSENTS TABLE
-- RGPD consent tracking
-- --------------------------------------------
CREATE TABLE user_consents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  consent_type VARCHAR(50) NOT NULL, -- e.g., 'privacy_policy', 'marketing', 'data_collection'
  consented BOOLEAN NOT NULL,
  consented_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address INET,

  -- One consent record per type per user
  CONSTRAINT unique_consent_per_type UNIQUE (user_id, consent_type)
);

-- Index for consent lookups
CREATE INDEX idx_user_consents_user_id ON user_consents(user_id);

-- ============================================
-- FUNCTIONS
-- ============================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- TRIGGERS
-- ============================================

-- Auto-update updated_at for profiles
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Auto-update updated_at for clothes
CREATE TRIGGER update_clothes_updated_at
  BEFORE UPDATE ON clothes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Auto-update updated_at for user_settings
CREATE TRIGGER update_user_settings_updated_at
  BEFORE UPDATE ON user_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE clothes ENABLE ROW LEVEL SECURITY;
ALTER TABLE outfit_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_consents ENABLE ROW LEVEL SECURITY;

-- --------------------------------------------
-- PROFILES POLICIES
-- Users can only access their own profiles
-- --------------------------------------------
CREATE POLICY "Users can view own profiles"
  ON profiles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own profiles"
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own profiles"
  ON profiles FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own profiles"
  ON profiles FOR DELETE
  USING (auth.uid() = user_id);

-- --------------------------------------------
-- CLOTHES POLICIES
-- Users can only access clothes of their profiles
-- --------------------------------------------
CREATE POLICY "Users can view own clothes"
  ON clothes FOR SELECT
  USING (
    profile_id IN (
      SELECT id FROM profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can create clothes for own profiles"
  ON clothes FOR INSERT
  WITH CHECK (
    profile_id IN (
      SELECT id FROM profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own clothes"
  ON clothes FOR UPDATE
  USING (
    profile_id IN (
      SELECT id FROM profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete own clothes"
  ON clothes FOR DELETE
  USING (
    profile_id IN (
      SELECT id FROM profiles WHERE user_id = auth.uid()
    )
  );

-- --------------------------------------------
-- OUTFIT RECOMMENDATIONS POLICIES
-- Users can only access recommendations of their profiles
-- --------------------------------------------
CREATE POLICY "Users can view own recommendations"
  ON outfit_recommendations FOR SELECT
  USING (
    profile_id IN (
      SELECT id FROM profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can create recommendations for own profiles"
  ON outfit_recommendations FOR INSERT
  WITH CHECK (
    profile_id IN (
      SELECT id FROM profiles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own recommendations"
  ON outfit_recommendations FOR UPDATE
  USING (
    profile_id IN (
      SELECT id FROM profiles WHERE user_id = auth.uid()
    )
  );

-- --------------------------------------------
-- USER SETTINGS POLICIES
-- Users can only access their own settings
-- --------------------------------------------
CREATE POLICY "Users can view own settings"
  ON user_settings FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own settings"
  ON user_settings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own settings"
  ON user_settings FOR UPDATE
  USING (auth.uid() = user_id);

-- --------------------------------------------
-- USER CONSENTS POLICIES
-- Users can only access their own consents
-- --------------------------------------------
CREATE POLICY "Users can view own consents"
  ON user_consents FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own consents"
  ON user_consents FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own consents"
  ON user_consents FOR UPDATE
  USING (auth.uid() = user_id);

-- ============================================
-- COMMENTS
-- ============================================
COMMENT ON TABLE profiles IS 'User profiles for multi-profile support (max 3 for MVP)';
COMMENT ON TABLE clothes IS 'Clothing items in the wardrobe, linked to profiles';
COMMENT ON TABLE outfit_recommendations IS 'Daily outfit recommendations generated by algorithm';
COMMENT ON TABLE user_settings IS 'User preferences and subscription status';
COMMENT ON TABLE user_consents IS 'RGPD consent tracking';
